[default.extend-words]
"terminaison" = "terminaison"
"explicite" = "explicite"
"composants" = "composants"
"sur" = "sur"
"verifie" = "verifie"
"projet" = "projet"
"cours" = "cours"
"supporte" = "supporte"
"informations" = "informations"
"presse" = "presse"
"pression" = "pression"
"copie" = "copie"
"celle" = "celle"
"complet" = "complet"
"principales" = "principales"
"moteur" = "moteur"
"registre" = "registre"
"restauration" = "restauration"
"remplace" = "remplace"
"partiel" = "partiel"
"exemple" = "exemple"
"valide" = "valide"
"invalide" = "invalide"
"branche" = "branche"
"bord" = "bord"
"contient" = "contient"
"environnement" = "environnement"
"fonctions" = "fonctions"
"commandes" = "commandes"
"adresse" = "adresse"
"authentification" = "authentification"
"configurables" = "configurables"
"correspondant" = "correspondant"
"langage" = "langage"
"certificat" = "certificat"
"certificats" = "certificats"
"algorithme" = "algorithme"
"algorithmes" = "algorithmes"
"commentaires" = "commentaires"
"familier" = "familier"
"maintenant" = "maintenant"
"approche" = "approche"
"appareil" = "appareil"
"persistant" = "persistant"
"installes" = "installes"
"pont" = "pont"
"effet" = "effet"
"reste" = "reste"
"ajustement" = "ajustement"
"bulle" = "bulle"
"exercice" = "exercice"
"autorisation" = "autorisation"
"connexion" = "connexion"
"absolue" = "absolue"
"principale" = "principale"
"principe" = "principe"
"principes" = "principes"
"authentifie" = "authentifie"
"authentifies" = "authentifies"
"Responsable" = "Responsable"
"mesures" = "mesures"
